# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31d468e2aa49c67e556531b34a7d5d6b07d2a1e5789dfc1dcc94f63e3f950a78bbe2d8c4a4bb817e7aaaf0f001286b3cb4de79e32f75f48e9308ce418aabb33

test:
  secret_key_base: e0a003ae158986845aa6171039354583f0e6cfef522c8e020492dff3795ef487cab89eae41096868facc7b9d67d974afa1e1f9f9d96bd5d6ee76a61d4b5408ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
